# Generated by Django 5.1 on 2025-06-22 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('logistics', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentrecord',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentrecord',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.equipmenttype'),
        ),
        migrations.AddField(
            model_name='assignmentrecord',
            name='issuing_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.base'),
        ),
        migrations.AddField(
            model_name='expenditurerecord',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.base'),
        ),
        migrations.AddField(
            model_name='expenditurerecord',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.equipmenttype'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.equipmenttype'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='from_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='users.base'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='to_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='users.base'),
        ),
    ]
