# Generated by Django 5.1 on 2025-06-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventory',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.base'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.equipmenttype'),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.base'),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.equipmenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='assetinventory',
            unique_together={('equipment_type', 'base')},
        ),
    ]
